### ISSUE TITLE
cuda and cudnn version

### ISSUE THREAD

**Issue by dzy666fly** [ChirikjianLab/deformable_ravens_vf#1]
Hello! Thanks for sharing code. When creating the envrionement with `conda ... python=3.8` and `./install_python_ubuntu.sh`, I'm struggling for the compatible version of cuda. So which cuda version should I select if using `conda install`? Or which cuda and cudnn version if selected from nvidia website?

**Comment by hongtaowu67** [comment]
I believe the cuda and cudnn versions should be matched with the tensorflow version and the nvidia driver version. So it depends on your graphic card and the nvidia driver version. You may find more information [here](https://docs.nvidia.com/cuda/cuda-toolkit-release-notes/index.html).
